### ISSUE TITLE
breadcrumb menu show only few categories

### ISSUE THREAD

**Issue by eninja** [Sajaki/BreadcrumbMenu#2]
![2017-08-24 15_44_05-greenshot](https://user-images.githubusercontent.com/1219089/29669278-2f8d91ac-88e3-11e7-8bab-3c2bc3bc992f.png)
only 1,5 category :(

**Comment by Galixte** [comment]
@eninja ```1,5``` what does that means?

**Comment by eninja** [comment]
one category and half of second if i hover on _Spolecznosc_

**Comment by Galixte** [comment]
Maybe too much forums.

Hi @Sajaki, could you take a look, please?

**Comment by avandenberghe** [comment]
could you try with v1.0.7 please?
